### ISSUE TITLE
Comment linkParams are inconsistent

### ISSUE THREAD

**Issue by zrpnr** [gabesullice/fluid_comment#19]
The links in a comment have different values for `meta.linkParams`

- self: linkParams is an array `["self", "https://jsonapi.org/profiles/drupal/hypermedia/#update", "https://jsonapi.org/profiles/drupal/hypermedia/#delete"]`
- reply, unpublish, publish: linkParams is an object, with a property `rel` which is an array containing a single uri `["https://jsonapi.org/profiles/drupal/hypermedia/#update"]`

**Comment by gabesullice** [comment]
I'm pretty sure that I already fixed this. You'll just need to pull the latest version of `jsonapi_hypermedia`

**Comment by zrpnr** [comment]
I know you did- it just seemed to have reverted. I had simplified the code a lot to fetch those urls and now it is back to being different for `self`.
I have the latest jsonapi_hypermedia, at commit `843786a` is that right?

**Comment by gabesullice** [comment]
Hmm... should be.

Can you paste your JSON response body?

**Comment by zrpnr** [comment]
the "links" from a single comment
```json
"links": {
    "reply": {
        "href": "http://drupal.test/jsonapi/node/article/e3a6bce2-445b-467d-8a09-7f51090ee4a4/comment/12585006-d355-45c7-ba55-893dd4878cbb/replies",
        "meta": {
            "linkParams": {
                "rel": [
                    "https://jsonapi.org/profiles/drupal/hypermedia/#add"
                ]
            }
        }
    },
    "self": {
        "href": "http://drupal.test/jsonapi/comment/comment/12585006-d355-45c7-ba55-893dd4878cbb",
        "meta": {
            "linkParams": [
                "self",
                "https://jsonapi.org/profiles/drupal/hypermedia/#update",
                "https://jsonapi.org/profiles/drupal/hypermedia/#delete"
            ]
        }
    },
    "unpublish": {
        "href": "http://drupal.test/jsonapi/comment/comment/12585006-d355-45c7-ba55-893dd4878cbb",
        "meta": {
            "linkParams": {
                "rel": [
                    "https://jsonapi.org/profiles/drupal/hypermedia/#update"
                ],
                "data": {
                    "type": "comment--comment",
                    "id": "12585006-d355-45c7-ba55-893dd4878cbb",
                    "attributes": {
                        "status": 0
                    }
                }
            }
        }
    }
}
```

**Comment by gabesullice** [comment]
@zrpnr said this was fixed in Slack. Fluid Comment requires this core patch: https://www.drupal.org/project/drupal/issues/3052931#comment-13097673
