### ISSUE TITLE
The first comments on a node do not appear without a cache clear

### ISSUE THREAD

**Issue by zrpnr** [gabesullice/fluid_comment#28]
the comments url returns 0 results with the `include` param until a cache clear.

Steps to reproduce:

1. create a node that has open comments
2. use fluid comment to post
3. comments do not appear
4. GET the comments url for this node with postman, include=uid.user_picture - no results
5. GET the comments url for this node with postman, no include - results appear
6. clear cache - comments appear on node

**Comment by zrpnr** [comment]
@gabesullice mentioned this is likely related to cache tags and the commentlist.

**Comment by gabesullice** [comment]
See: https://www.drupal.org/project/jsonapi_comment/issues/3055469
