### ISSUE TITLE
Remove demo folder

### ISSUE THREAD

**Issue by zrpnr** [gabesullice/fluid_comment#30]
I don't think this is being used, and it requires a few lines of "exports" from the main index.js. Planning to remove this folder and other unnecessary code from the beginning of this project.

**Comment by gabesullice** [comment]
Makes sense to me. It's a leftover from the original DBUG demo.

**Comment by gabesullice** [comment]
While working on #32 I realized that these `export`s can be removed once we do this.

https://github.com/gabesullice/fluid_comment/blob/4554ef813b2ba0346c4d0c62969d27613009be8b/js/src/index.js#L8

**Comment by zrpnr** [comment]
I got started down this path because of trying to remove those `export` and getting an error because the demo depended on them... then tried to remove the demo folder and got a build error... so it meant replacing the tooling...
classic javascript problems.
