### ISSUE TITLE
Allow anonymous comments

### ISSUE THREAD

**Issue by zrpnr** [gabesullice/fluid_comment#4]
If anonymous role has the Post Comments permission, new comments will appear as unpublished to admin.

* Add a class for unpublished vs published (comment--unpublished)
* link to "Approve" should appear for admin with permission.

**Comment by gabesullice** [comment]
https://git.drupalcode.org/project/jsonapi_hypermedia/commit/0df573c18003c5fdb9a8d96d99f59881f5e2d580

**Comment by gabesullice** [comment]
> Add a class for unpublished vs published (comment--unpublished)
Do you need anything from the backend for this or is the "publish" link enough of a flag?

**Comment by zrpnr** [comment]
I'm going to make some changes in the Wrapper, currently there is a hard check for `loggedIn` but this should use the presence of #add to check whether the form should appear per https://github.com/gabesullice/fluid_comment/pull/14

**Comment by zrpnr** [comment]
This should be resolved, the last reference to anonymous users was removed with https://github.com/gabesullice/fluid_comment/pull/29
