### ISSUE TITLE
Edit / Delete links

### ISSUE THREAD

**Issue by zrpnr** [gabesullice/fluid_comment#5]
Admin with permission should see Edit and Delete links.
These should be provided by the jsonapi_hypermedia module.

Open questions:
1. Should the Edit take place inline? Would that form need save/cancel buttons?
2. Should the Delete happen without a prompt? Or have confirm/cancel buttons?

**Comment by gabesullice** [comment]
Should the Edit take place inline? I think so.
Would that form need save/cancel buttons? I think so (auto-save is really hard on the backend since it creates dozens of revisions right now)
Should the Delete happen without a prompt? No.
Or have confirm/cancel buttons? I think it should have buttons.

**Comment by zrpnr** [comment]
When I was working on the publish / unpublish I wondered if we could just have all of those different links have an inline "confirm / cancel" before actually sending the request.

Then the only difference is "edit" would also have a form to populate its data.

**Comment by gabesullice** [comment]
Makes sense to me!

**Comment by zrpnr** [comment]
This should be resolved with https://github.com/gabesullice/fluid_comment/pull/27

**Comment by zrpnr** [comment]
Closing this issue, made https://github.com/gabesullice/fluid_comment/issues/38 to deal with the edit and reply forms not having `format`
